### ISSUE TITLE
Single form

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#11]
i suggest the item and files submission form combined to a single form if that's possible

**Comment by ggoffy** [comment]
in a first step I have still split it

**Comment by ggoffy** [comment]
currently you have two options:
upload documents directly after creation of item:
![grafik](https://user-images.githubusercontent.com/7547661/118933375-66993580-b949-11eb-903b-e95bb06f285b.png)

or add documents later:
![grafik](https://user-images.githubusercontent.com/7547661/118933241-42d5ef80-b949-11eb-9590-502eb5418c0f.png)

if this ok for you?

**Comment by mjoelweb** [comment]
1. Will be nice if it can be done in single one click, enter text select file then submit like the publisher module
2. typo 'submit and and file'

**Comment by ggoffy** [comment]
multiupload implemented
![grafik](https://user-images.githubusercontent.com/7547661/119165832-368f8680-ba5e-11eb-9914-3863f81690f1.png)

you can define max number of uploads per item in module preferences
