### ISSUE TITLE
Profile module custom field

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#14]
In my xoops setup, ive installed the Profile module and in the module i have these custom field
a. Job Position 
b. Department

i got this code somewhere in the xoops.org forum to use this code in any module

```
global $xoopsUser; 
$loggedinuid = is_object($xoopsUser) ? $xoopsUser->getVar('uid') : 0;  
$profile_handler =xoops_getmodulehandler('profile','profile');
 if (is_object($xoopsUser))  {//if member
$profile = $profile_handler->get($loggedinuid); }
$jobposition=$profile->getVar('Position');
$department=$profile->getVar('Department');

```
will be nice if wgdiaries can include any profile module custom fields automatically for use in the wgdiaries template to be setup in the preferences

**Comment by ggoffy** [comment]
specific adaptions can't be implemented generally. I recommend that you implement such additional things later yourself ;)
