### ISSUE TITLE
Simple Calendar system

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#15]
a simple archive /calendar to be shown only to user which day he/she has made an entries

**Comment by ggoffy** [comment]
![grafik](https://user-images.githubusercontent.com/7547661/119360297-c1fd5780-bcaa-11eb-9910-efabd49be216.png)

**Comment by mjoelweb** [comment]
Hi Goffy 

nice, suggestion to be consider
a. ability to select future or past date in calendar
b. make the day clickable

**Comment by ggoffy** [comment]
currently I am not planning to create a calendar module

**Comment by mjoelweb** [comment]
can we have an archive like this by year/month ? user can only  see their own item archive
https://xoops.org/modules/publisher/archive.php
https://xoops.org/modules/news/archive.php

archive can be arrange by year..like in this example 
https://xoops.org/modules/newbb/viewtopic.php?start=0&topic_id=37530&order=ASC&status=&mode=0

**Comment by ggoffy** [comment]
added a calendar page where you can

- click on event for editing it
- click on "plus" to add new event to selected date

![grafik](https://user-images.githubusercontent.com/7547661/120344506-ef28b600-c2f9-11eb-83dd-465a6318cf16.png)

**Comment by mjoelweb** [comment]
a. missing logo image in the archive page
![Untitled](https://user-images.githubusercontent.com/84079049/120643701-107bd480-c4a9-11eb-8ecd-51c275fbd97c.jpg)

b. can we have template like this..since over the years the list and archive page will be long
![Untitled](https://user-images.githubusercontent.com/84079049/120644620-1faf5200-c4aa-11eb-9b6c-83922808185a.jpg)

**Comment by ggoffy** [comment]
both is done
