### ISSUE TITLE
Printer Friendly Page /pdf support

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#17]
Printable friendly page or print as pdf (tcpdf support)

**Comment by ggoffy** [comment]
implemented output for print

**Comment by mjoelweb** [comment]
can the single item also be printable

**Comment by mjoelweb** [comment]
> implemented output for print

i really like the filter by date function,,thank you goffy
can the single item also be printable

**Comment by ggoffy** [comment]
done
![grafik](https://user-images.githubusercontent.com/7547661/120073329-1aac6600-c098-11eb-9377-6d1c462e03ea.png)
