### ISSUE TITLE
item can be comment

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#18]
user or admin can choose who can comment for entry..

example set it to project leader or head of department only

**Comment by ggoffy** [comment]
comments for items are activated. detailed permission rules will be implemented later

**Comment by ggoffy** [comment]
user which are allowed to edit item are also allowed to submit/view comments.

is this ok for you?

**Comment by mjoelweb** [comment]
> user which are allowed to edit item are also allowed to submit/view comments.
> 
> is this ok for you?

so that will logged in user an admin only

**Comment by ggoffy** [comment]
users with 

- Permissions global to edit
- Permissions to edit items of group
- Permissions to edit own items
