### ISSUE TITLE
User can post entries for any given date

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/wgdiaries#2]
I suggest to store the information "date and time from" - "date and time to"
because then we can calculate the time for each day

**Comment by mjoelweb** [comment]
maybe if possible user can choose single day entry or multiple day

**Comment by ggoffy** [comment]
what do you mean?
implementing "16.05.2021 08:00" to "16.05.2021 16:00" for one single item is foreseen
implementing "15.05.2021 08:00" to "15.05.2021 16:00" plus "16.05.2021 08:00" to "16.05.2021 16:00" for one single item is tricky

**Comment by mjoelweb** [comment]
i use the wrong word we can keep it as now

maybe this can be done in template..name report
when choose day event is single 16.05.2021 08:00" to "16.05.2021 17:00  (single end of day report of 16th May 8.00am to 5.00pm) else 
16.05.2021 08:00 to 18.05.2021 18:00 (Multiple day report from 16-18th May)

![35](https://user-images.githubusercontent.com/84079049/118883857-52910c00-b928-11eb-896d-ce2ad76916e0.jpg)

**Comment by mjoelweb** [comment]
i have another idea to be consider  if this possible maybe,
we allow to select only single date and then we can add time task is done and status of task

select day - example 23/5/2021

9.00am - 10.00am
a. Remark/KPI - Status (done/in progress etc)
b. Remark/KPI-  Status 

10.00 - 1.00pm
a. Remark - Status
b. Remark - Status

2.00pm - 6.00pm
a. remark - status

and then at bottom user can enter Daily summary

**Comment by ggoffy** [comment]
you can enter now multiple items per day and add to each remarks/categories

enter a daily summary is not necessary, as this can be caluclated automatically

if it is ok for you now please close the issue

**Comment by mjoelweb** [comment]
thank you, yes issue can be close

i didnt see any close issue button for this issue

![Untitled](https://user-images.githubusercontent.com/84079049/119739393-c1381180-beb4-11eb-9e9d-d2ca2cda4003.jpg)

**Comment by ggoffy** [comment]
maybe because I opened it :)
