### ISSUE TITLE
Add Group Members in Batch

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#24]
option to add group members in batch for easy group management

![img5e2d3149d6195](https://user-images.githubusercontent.com/84079049/118805074-15049280-b8d8-11eb-804a-a1833c9e094e.jpg)

maybe can create interface example like xoops group manager module but the user can be put into wgdiaries groups in batch
https://xoops.org/modules/publisher/item.php?itemid=5985&com_id=57875&com_rootid=57872&

**Comment by ggoffy** [comment]
Hi

I added a simple possibility to link users to groups
![grafik](https://user-images.githubusercontent.com/7547661/118890033-4b550880-b8fe-11eb-8d6d-ac0fb5556535.png)

**Comment by ggoffy** [comment]
I integrated the selection of users into edit form of group

**Comment by mjoelweb** [comment]
> I integrated the selection of users into edit form of group

1. option to use real name in preferences for name of user
2. Selection of user is not saved currently

**Comment by mjoelweb** [comment]
Hi Goffy by the way it is possible to use XOOPS Group instead of creating another Group Function ? so i will select permission based on existing xoops groups

example in one of my site i already hve these groups existed
- Head of Departments
- Project Supervisors
- Finance 
- Human Resource

but selection of users to group maybe can still be retain in the module, so we can directly know who is in the group or not

**Comment by ggoffy** [comment]
> 1. option to use real name in preferences for name of user

done

**Comment by ggoffy** [comment]
> 2.  Selection of user is not saved currently

for me it works. did you run update of module?

**Comment by ggoffy** [comment]
> use XOOPS Group instead of creating another Group Function

yes, of course this is possible.
if you have more or less always the same groups and group/user combination it make sense to use xoops system

I would not use xoops system if  you are very often change groups and group/user combination (e.g. if you are using it for temporary projects). In order to get this flexibility I implemented module own group/user management

**Comment by ggoffy** [comment]
>  use XOOPS Group instead of creating another Group

if think you are right. I will make a step back to xoops group and user system

**Comment by ggoffy** [comment]
I will add the  interface from xoops group manager module

**Comment by ggoffy** [comment]
why not using xoops group manager module??
I can update it to be ready for php8

**Comment by mjoelweb** [comment]
> why not using xoops group manager module??
> I can update it to be ready for php8

That will be great..wish if possible we can move user by batch in that module

**Comment by ggoffy** [comment]
xoops group manager module is ready for php8. please download last version from github
