### ISSUE TITLE
Hide fields in form in preferences

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#38]
Option to hide fields in form and also in item page

 Example
a. Group
b. Comments
c. Upload files (disable upload files)
d. Date Created (when disable automatically choose today date) 
e. Submitter (when disable automatically choose current logged in user)

**Comment by mjoelweb** [comment]
by the way, is the comment field in the form is use for total comment of the item ?

**Comment by ggoffy** [comment]
most of these field are only visible for you as Xoops Webmaster. Login in as Xoops Registered Users (or another one of your roles, which is not webmaster) then you will see that these fields aren't available anymore ;)

**Comment by ggoffy** [comment]
> by the way, is the comment field in the form is use for total comment of the item ?

yes, and it will be updated automatically. it is only visible for you if you have to correct it manually
