### ISSUE TITLE
admin can see all entries by a particular user

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/wgdiaries#4]
I suggest following permission rules:

- can see all
- can see own items
- can see items of group (if we implement group and user system https://github.com/XoopsModules25x/wgWfhDiaries/issues/5)

**Comment by mjoelweb** [comment]
can comment item - example head of department

**Comment by ggoffy** [comment]
following permission rules are implemented currently:

- Permissions global to submit
- Permissions global to edit
- Permissions global to view
- Permissions to submit items
- Permissions to edit items of group
- Permissions to view items of group
- Permissions to edit own items
- Permissions to view own items
