### ISSUE TITLE
title for item page

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#40]
Option for user to add title for report or we as admin can define as default as example

"RealName - Job Report (13th Jun 2021)

**Comment by ggoffy** [comment]
item page title shows now "Realname - Details of No. 2 - 05/17/2021"

**Comment by mjoelweb** [comment]
can this be included in the form so user have the option to edit it?

**Comment by ggoffy** [comment]
I would not create a new field only for title for displaying item

We should already available data of an item

**Comment by mjoelweb** [comment]
yes the name field can be use as title
