### ISSUE TITLE
Item image

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#49]
Suggestion to be consider

1. Option for user to upload  single image for item ( something like item logo..different from uploading files)
2.  Item thumbnail to be shown in item list 
3.  Image will be display at top of item page
4.  Default image/ thumbnail will be display in item page or item list if no image is uploaded

**Comment by ggoffy** [comment]
>     2\. Item thumbnail to be shown in item list

is already done in last version

**Comment by ggoffy** [comment]
concerning item logo:
if I would use it for daily documentation what I have done I can't imagine which sense a logo make :|

what I can imagine is that we implement categories/classes, e.g.

- planning phase
- execution phase
- evaluation phase

or usage of tags

**Comment by mjoelweb** [comment]
a. item logo for future use like a main or representative  image for an item, we can make the template look nice with image for every item
b. Tag support will be awesome
c. Category : In progress/ done etc

**Comment by ggoffy** [comment]
categories implemented
item logo implemented
item tags implemented
