### ISSUE TITLE
group and user system

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/wgdiaries#5]
I think it would be nice to implement a group and user system
then we can group users in a team, in a project or whatever we want, and team or project leader can see items of member of the group

**Comment by ggoffy** [comment]
implented in general

**Comment by ggoffy** [comment]
how should I prepare:
one user can only be in one group?
one user can only be in multiple groups?

**Comment by alain01** [comment]
one user can be in multiple groups ;-)

**Comment by mjoelweb** [comment]
one user in multiple groups

**Comment by ggoffy** [comment]
implemented
