### ISSUE TITLE
missing column header

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#52]
![column](https://user-images.githubusercontent.com/84079049/119404801-e42ac000-bd12-11eb-82a8-b3b286a45f52.jpg)

**Comment by ggoffy** [comment]
cant reproduce :(

is this index.php?

for me it looks good:
![grafik](https://user-images.githubusercontent.com/7547661/119411189-491df000-bcea-11eb-9cca-95d4e94eccd8.png)

**Comment by mjoelweb** [comment]
yes it is index php, 

weird, i use sample data and John doe is my real name set in xoops
i tried remove my real name and John Doe is replace by my username admin

![column](https://user-images.githubusercontent.com/84079049/119480662-7a4afe80-bd84-11eb-9256-a8c9beb6c9b2.jpg)

**Comment by ggoffy** [comment]
did you adapt the templates?

**Comment by mjoelweb** [comment]
no at the moment..

**Comment by ggoffy** [comment]
if you run module update and clean the cache: is then displaying as it should be?

**Comment by mjoelweb** [comment]
same result, i also clean it manually

i use the sample data in the last update, my lastitem is not correct
![column](https://user-images.githubusercontent.com/84079049/119581563-64c1ed00-bdf5-11eb-9eb1-a2e2f350970d.jpg)

**Comment by ggoffy** [comment]
this is strange. please goto admin/index.php, click on "Export tables to YAML", zip the complete wgdiaries folder and send me by mail

**Comment by mjoelweb** [comment]
Hi goffy may i know your email, maybe you can pm me on xoops.org

**Comment by ggoffy** [comment]
this is still strange, there must be "somewhere something old" 
I took your module, installed, loaded test data and it looks like:
![grafik](https://user-images.githubusercontent.com/7547661/119691392-d2e4cf00-be4a-11eb-9346-7d7cdc1ed822.png)

**Comment by ggoffy** [comment]
please uninstall, delete complete folder wgdiaries, and take current version from github (broken images are repaired).
if display is still, maybe there is something in your theme, therefore try it with another theme

**Comment by mjoelweb** [comment]
this is strange, i didnt have any template in my theme and when i tried new update from github i will always delete the old files
i tried with a new xoops installation all is now ok..sorry and thank you
