### ISSUE TITLE
sort item option 

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#62]
sort item list option in admin preferences for front end and backend

eg sort by date, category etc

**Comment by ggoffy** [comment]
sorting basically is ok, but for e.g. sorting category I have the problem that in items table I store the catid, and if I sort by catid it is maybe not the same sorting as you have set with the weight for each category.

**Comment by mjoelweb** [comment]
sort by item date or submission date i think will be sufficient

**Comment by ggoffy** [comment]
![grafik](https://user-images.githubusercontent.com/7547661/120103463-f6ac5b80-c14f-11eb-9ce9-061c08a21f16.png)

**Comment by mjoelweb** [comment]
can the item list in index and also in admin index be sort ?

**Comment by ggoffy** [comment]
my opinion: in the index page there should always be an overview of last activities

in admin page I can add the filter including the sorting

**Comment by mjoelweb** [comment]
default sort option will be by last activities but for  more option for other use of the module sortable by date for index can also be consider :-)

**Comment by ggoffy** [comment]
added sorting index page

**Comment by ggoffy** [comment]
archive page added
https://github.com/XoopsModules25x/wgdiaries/pull/72
