### ISSUE TITLE
user page

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/wgdiaries#63]
i have another suggestion to be consider

if in future if i would like to open access of the diary to other user can each registered user in my xoops site  to have their own page id 

example my xoops uid is 20 so i have a page something like modules/wgdiaries/author.php?uid=20

in the page all the list entry made by user uid 20 are listed

and maybe user themselves can set their page to private or public

**Comment by ggoffy** [comment]
if I understand in the right way: this sound more like blog or social module (like small world), where you can add something, make it public or only readable for specific groups and so on

**Comment by mjoelweb** [comment]
Can be consider next time

I have a custom staff list and would like in future..any user can click a button and bring them to the diary for a staff

**Comment by ggoffy** [comment]
1) if it is only to display the list of all others or of all others of my group it is possible with additional permissions.
2) if you want to have it for each item different (public/private) and for each item different who is allowed to see then it will be more complex

1 or 2 ?

**Comment by mjoelweb** [comment]
number 1 - all user regardless they have entry or not will have a page id if thats possible

**Comment by ggoffy** [comment]
done

please run module update as there is a new template

let mme know whether it is ok for you

**Comment by mjoelweb** [comment]
very nice goffy..thank you very much 

a. for consistency maybe show blank avatar (blank.gif) for user that doesn't have avatar
b. if i wish to include user with 0 item, where should i edit the code ?
c. i tried to change the url to user id with 0 entry, it is just empty maybe can put some text like user dont have any entry yet

**Comment by ggoffy** [comment]
the goal was to show the items of other users
does it make sense to show users without items?

**Comment by mjoelweb** [comment]
> the goal was to show the items of other users
> does it make sense to show users without items?

Just to know which of my staff who did not update their diary or made any single entry...

Maybe can made it as option in preferences if that possible

**Comment by ggoffy** [comment]
done

**Comment by mjoelweb** [comment]
Goffy Thank you very much 👍 🥇
