### ISSUE TITLE
Wrong date 1970

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wgdiaries#8]
![image](https://user-images.githubusercontent.com/613686/118353962-ae2d5500-b536-11eb-9c60-6e07a88fced3.png)

**Comment by ggoffy** [comment]
realised already and already solved also in modulebuilder to get proper default
https://github.com/XoopsModules25x/modulebuilder/pull/90

**Comment by ggoffy** [comment]
thank you
